version: "3.7"
services:
  wedding:
    container_name: wedding
    image: harbor.chlin.tk/vue/wedding:${TAG}
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - 8050:8050
    restart: always
    networks: 
      - nginx
networks:
  nginx:
    external: true
    name: nginx
